"""initial schema

Revision ID: 15e5a9d995a5
Revises:
Create Date: 2026-08-25 20:01:42.678632
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from funflix.models.base import UTCDateTime

revision: str = "15e5a9d995a5"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("norm_key", sa.String(length=255), nullable=False),
        sa.Column("original_title", sa.String(length=255), nullable=True),
        sa.Column(
            "media_type",
            sa.Enum(
                "movie",
                "tv",
                "anime",
                "variety",
                "documentary",
                "unknown",
                name="mediatype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "aliases", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("douban_id", sa.String(length=32), nullable=True),
        sa.Column("imdb_id", sa.String(length=16), nullable=True),
        sa.Column("poster_url", sa.String(length=1024), nullable=True),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("resource_count", sa.Integer(), nullable=False),
        sa.Column("valid_resource_count", sa.Integer(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media")),
        sa.UniqueConstraint("norm_key", "media_type", "year", name="uq_media_identity"),
    )
    with op.batch_alter_table("media", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_media_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_media_douban_id"), ["douban_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_media_imdb_id"), ["imdb_id"], unique=False)
        batch_op.create_index("ix_media_title", ["title"], unique=False)
        batch_op.create_index(batch_op.f("ix_media_tmdb_id"), ["tmdb_id"], unique=False)

    op.create_table(
        "source",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "telegram",
                "weibo",
                "forum",
                "rss",
                "manual",
                "api",
                "unknown",
                name="sourcetype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("identifier", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("fetch_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("max_pages_per_fetch", sa.Integer(), nullable=False),
        sa.Column("cursor_message_id", sa.String(length=64), nullable=True),
        sa.Column("cursor_published_at", UTCDateTime(), nullable=True),
        sa.Column("last_fetched_at", UTCDateTime(), nullable=True),
        sa.Column("last_success_at", UTCDateTime(), nullable=True),
        sa.Column("next_fetch_at", UTCDateTime(), nullable=True),
        sa.Column("lease_until", UTCDateTime(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("total_collected", sa.Integer(), nullable=False),
        sa.Column(
            "extra", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source")),
        sa.UniqueConstraint("source_type", "identifier", name="uq_source_type_identifier"),
    )
    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_source_created_at"), ["created_at"], unique=False)
        batch_op.create_index("ix_source_fetch_queue", ["enabled", "next_fetch_at"], unique=False)

    op.create_table(
        "raw_document",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum(
                "telegram",
                "weibo",
                "forum",
                "rss",
                "manual",
                "api",
                "unknown",
                name="sourcetype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_name", sa.String(length=128), nullable=True),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column("source_msg_id", sa.String(length=128), nullable=True),
        sa.Column("published_at", UTCDateTime(), nullable=True),
        sa.Column("collected_at", UTCDateTime(), nullable=False),
        sa.Column(
            "extra", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column(
            "parse_status",
            sa.Enum(
                "pending",
                "running",
                "done",
                "failed",
                "skipped",
                name="parsestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("parse_attempts", sa.Integer(), nullable=False),
        sa.Column("parse_error", sa.Text(), nullable=True),
        sa.Column("lease_until", UTCDateTime(), nullable=True),
        sa.Column("next_parse_at", UTCDateTime(), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_raw_document_source_id_source"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_document")),
        sa.UniqueConstraint("content_hash", name=op.f("uq_raw_document_content_hash")),
    )
    with op.batch_alter_table("raw_document", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_raw_document_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_raw_document_parse_queue", ["parse_status", "next_parse_at"], unique=False
        )
        batch_op.create_index(
            "ix_raw_document_source", ["source_type", "source_name", "published_at"], unique=False
        )
        batch_op.create_index(
            "ix_raw_document_source_msg", ["source_id", "source_msg_id"], unique=False
        )

    op.create_table(
        "extraction",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "raw_document_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=16), nullable=False),
        sa.Column(
            "output", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "stats", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["raw_document_id"],
            ["raw_document.id"],
            name=op.f("fk_extraction_raw_document_id_raw_document"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extraction")),
        sa.UniqueConstraint(
            "raw_document_id", "model", "prompt_version", name="uq_extraction_doc_model_version"
        ),
    )
    with op.batch_alter_table("extraction", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_extraction_created_at"), ["created_at"], unique=False)

    op.create_table(
        "resource",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("media_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column(
            "raw_document_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "provider",
            sa.Enum(
                "quark",
                "uc",
                "alipan",
                "baidu",
                "pan115",
                "lanzou",
                "tianyi",
                "xunlei",
                "magnet",
                "other",
                name="provider",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("share_id", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("passcode", sa.String(length=32), nullable=True),
        sa.Column("title_raw", sa.String(length=512), nullable=True),
        sa.Column(
            "quality",
            sa.Enum(
                "4k", "1080p", "720p", "sd", "unknown", name="quality", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("episode_info", sa.String(length=64), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column(
            "check_status",
            sa.Enum(
                "unchecked",
                "checking",
                "valid",
                "invalid",
                "need_password",
                "rate_limited",
                "unsupported",
                "error",
                name="checkstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("check_attempts", sa.Integer(), nullable=False),
        sa.Column("last_checked_at", UTCDateTime(), nullable=True),
        sa.Column("next_check_at", UTCDateTime(), nullable=True),
        sa.Column("lease_until", UTCDateTime(), nullable=True),
        sa.Column("first_seen_at", UTCDateTime(), nullable=False),
        sa.Column("last_seen_at", UTCDateTime(), nullable=False),
        sa.Column("seen_count", sa.Integer(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_id"], ["media.id"], name=op.f("fk_resource_media_id_media"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["raw_document_id"],
            ["raw_document.id"],
            name=op.f("fk_resource_raw_document_id_raw_document"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resource")),
        sa.UniqueConstraint("provider", "share_id", name="uq_resource_provider_share"),
    )
    with op.batch_alter_table("resource", schema=None) as batch_op:
        batch_op.create_index(
            "ix_resource_check_queue", ["check_status", "next_check_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_resource_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            "ix_resource_media_status", ["media_id", "check_status"], unique=False
        )

    op.create_table(
        "link_check",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "resource_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("checked_at", UTCDateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "unchecked",
                "checking",
                "valid",
                "invalid",
                "need_password",
                "rate_limited",
                "unsupported",
                "error",
                name="checkstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("http_code", sa.Integer(), nullable=True),
        sa.Column("probe", sa.String(length=64), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resource.id"],
            name=op.f("fk_link_check_resource_id_resource"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_link_check")),
    )
    with op.batch_alter_table("link_check", schema=None) as batch_op:
        batch_op.create_index(
            "ix_link_check_resource_time", ["resource_id", "checked_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("link_check", schema=None) as batch_op:
        batch_op.drop_index("ix_link_check_resource_time")

    op.drop_table("link_check")
    with op.batch_alter_table("resource", schema=None) as batch_op:
        batch_op.drop_index("ix_resource_media_status")
        batch_op.drop_index(batch_op.f("ix_resource_created_at"))
        batch_op.drop_index("ix_resource_check_queue")

    op.drop_table("resource")
    with op.batch_alter_table("extraction", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_extraction_created_at"))

    op.drop_table("extraction")
    with op.batch_alter_table("raw_document", schema=None) as batch_op:
        batch_op.drop_index("ix_raw_document_source_msg")
        batch_op.drop_index("ix_raw_document_source")
        batch_op.drop_index("ix_raw_document_parse_queue")
        batch_op.drop_index(batch_op.f("ix_raw_document_created_at"))

    op.drop_table("raw_document")
    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.drop_index("ix_source_fetch_queue")
        batch_op.drop_index(batch_op.f("ix_source_created_at"))

    op.drop_table("source")
    with op.batch_alter_table("media", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_media_tmdb_id"))
        batch_op.drop_index("ix_media_title")
        batch_op.drop_index(batch_op.f("ix_media_imdb_id"))
        batch_op.drop_index(batch_op.f("ix_media_douban_id"))
        batch_op.drop_index(batch_op.f("ix_media_created_at"))

    op.drop_table("media")
    # ### end Alembic commands ###
