"""tags

Revision ID: 9036e3fe2a7e
Revises: ca05e404212a
Create Date: 2026-08-26 00:09:04.748923
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from funflix.models.base import UTCDateTime

revision: str = "9036e3fe2a7e"
down_revision: str | None = "ca05e404212a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "genre",
                "region",
                "language",
                "year",
                "other",
                name="tagkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("norm_key", sa.String(length=64), nullable=False),
        sa.Column("media_count", sa.Integer(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tag")),
        sa.UniqueConstraint("kind", "norm_key", name="uq_tag_kind_key"),
    )
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tag_created_at"), ["created_at"], unique=False)
        batch_op.create_index("ix_tag_kind_count", ["kind", "media_count"], unique=False)

    op.create_table(
        "media_tag",
        sa.Column("media_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("tag_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_id"], ["media.id"], name=op.f("fk_media_tag_media_id_media"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tag.id"], name=op.f("fk_media_tag_tag_id_tag"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("media_id", "tag_id", name=op.f("pk_media_tag")),
    )
    with op.batch_alter_table("media_tag", schema=None) as batch_op:
        batch_op.create_index("ix_media_tag_tag", ["tag_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("media_tag", schema=None) as batch_op:
        batch_op.drop_index("ix_media_tag_tag")

    op.drop_table("media_tag")
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.drop_index("ix_tag_kind_count")
        batch_op.drop_index(batch_op.f("ix_tag_created_at"))

    op.drop_table("tag")
    # ### end Alembic commands ###
