"""many-to-many media-resource, bidirectional cursors

Revision ID: ca05e404212a
Revises: 15e5a9d995a5
Create Date: 2026-08-25 22:57:19.896812
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from funflix.models.base import UTCDateTime

revision: str = "ca05e404212a"
down_revision: str | None = "15e5a9d995a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_resource",
        sa.Column("media_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "resource_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media.id"],
            name=op.f("fk_media_resource_media_id_media"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resource.id"],
            name=op.f("fk_media_resource_resource_id_resource"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("media_id", "resource_id", name=op.f("pk_media_resource")),
    )
    with op.batch_alter_table("media_resource", schema=None) as batch_op:
        batch_op.create_index("ix_media_resource_resource", ["resource_id"], unique=False)

    with op.batch_alter_table("resource", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resource_media_status"))
        batch_op.create_index("ix_resource_status", ["check_status"], unique=False)
        batch_op.drop_constraint(batch_op.f("fk_resource_media_id_media"), type_="foreignkey")
        batch_op.drop_column("media_id")

    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.add_column(sa.Column("backfill_cursor_id", sa.String(length=64), nullable=True))
        # 表里已有数据，NOT NULL 列必须带 server_default 才能加上去；
        # 建完再撤掉默认值，让"默认值"这件事只由应用层的模型定义说了算。
        batch_op.add_column(
            sa.Column("backfill_done", sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(
            sa.Column("backfill_pages_per_fetch", sa.Integer(), nullable=False, server_default="5")
        )
        batch_op.add_column(
            sa.Column("total_backfilled", sa.Integer(), nullable=False, server_default="0")
        )

    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.alter_column("backfill_done", server_default=None)
        batch_op.alter_column("backfill_pages_per_fetch", server_default=None)
        batch_op.alter_column("total_backfilled", server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.drop_column("total_backfilled")
        batch_op.drop_column("backfill_pages_per_fetch")
        batch_op.drop_column("backfill_done")
        batch_op.drop_column("backfill_cursor_id")

    with op.batch_alter_table("resource", schema=None) as batch_op:
        batch_op.add_column(sa.Column("media_id", sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_resource_media_id_media"),
            "media",
            ["media_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.drop_index("ix_resource_status")
        batch_op.create_index(
            batch_op.f("ix_resource_media_status"), ["media_id", "check_status"], unique=False
        )

    with op.batch_alter_table("media_resource", schema=None) as batch_op:
        batch_op.drop_index("ix_media_resource_resource")

    op.drop_table("media_resource")
    # ### end Alembic commands ###
